pool:
  demands: npm

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: Npm@1
  displayName: 'npm custom'
  inputs:
    command: custom
    workingDir: ./
    verbose: false
    customCommand: 'run build'

- task: ArchiveFiles@2
  displayName: 'Archive $(System.DefaultWorkingDirectory)/build'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
    archiveFile: '$(build.artifactstagingdirectory)/reactapp.zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
